source/usr/lib/mcvirt/parser.py

Argparser add description epilog to argument parser

---

Documentation/Cluster.rst

Document procedures for tearing down after failed cluster commands in MCVirt #45

Added documentation for recovering the cluster from various issues

---

source/usr/lib/mcvirt/mcvirt_config.py

* Added creation of root MCVirt data directory, /var/lib/mcvirt
* Updated data directory chmod to use constants from the 'stat' module

Updated check for MCVirt config directory to check for /var/lib/mcvirt

---

source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Fix arg parser ignore drbd non superuser

---

source/DEBIAN/control

Added libvirt-bin package dependency, as it is required for virsh

---

source/usr/lib/mcvirt/templates/domain.xml

Updated graphics for default domain from cirrus to vmvga

---

source/usr/lib/mcvirt/iso.py
source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/virtual_machine/disk_drive.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Created Iso class to manage ISOs and implement passing of Iso objects when attatching ISOs to VMs

Iso management

---

source/usr/lib/mcvirt/virtual_machine/hard_drive/config/base.py

This should help with DRBD syncronization issues

Changed hard drive mode for VMs to directsync

---

source/usr/lib/mcvirt/node/network.py
source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/test/node/network_tests.py

Added functionality to allow users to list networks on the node
Issue #56

List networks

---

source/usr/lib/mcvirt/node/drbd.py
source/usr/lib/mcvirt/parser.py

Added method for creating table of DRBD volumes and added arguments to parser to show table

---

source/usr/lib/mcvirt/cluster/remote.py
source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/test/virtual_machine/virtual_machine_tests.py
source/usr/lib/mcvirt/virtual_machine/network_adapter.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Validate networks when creating/attaching an adapter to a VM #89

Ensure network exists when adding new network adapter to a VM

---

source/usr/lib/mcvirt/test/run_tests.py
source/usr/lib/mcvirt/test/update_tests.py
source/usr/lib/mcvirt/virtual_machine/network_adapter.py

Added unit test to test removal of a network interface from a VM
Removing a network from a VM throws an exception #95

Fix network interface removal from a VM

---

source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/test/virtual_machine/virtual_machine_tests.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Added unittest to reset a VM and to attempt to reset a stopped VM
Implement 'reset' into MCVirt #40

Added reset functionaltiy to VM and parser

---

source/usr/lib/mcvirt/parser.py

Parser description is line-wrapped #112

Specified formatter class for parser, so that the description/epilog are not line-wrapped

---

source/usr/lib/mcvirt/mcvirt_config.py

Documentation for removing default network no longer works #53

Added default libvirt network to default MCVirt configuration

---

Documentation/Installation.rst
Documentation/Permissions.rst

See https://github.com/ITDevLtd/MCVirt/blob/document-sudo-config/Documentation/Installation.rst
Document configuration of sudo for use with MCVirt #42

Added documentation about configuring sudo rules

---

source/usr/lib/mcvirt/config_file.py
source/usr/lib/mcvirt/mcvirt_config.py

Permissions are not set for remote node configurations in git repository #102

Added function to set permissions on MCVirt data directories

---

CHANGES

Added 'CHANGES' file containing release notes for current release

---

source/usr/lib/mcvirt/cluster/remote.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Added ability to remotely start/stop/reset VMs and functionality to obtain VM information from a remote node.
Implement basic VM control from remote node #101

Perform basic remote vm controls

---

source/usr/lib/mcvirt/config_file.py
source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/test/virtual_machine/virtual_machine_tests.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/base.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/config/base.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/config/drbd.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/config/local.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/drbd.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/factory.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/local.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine_config.py

Support selection of block device driver (ide/scsi/virtio) #116

Implement disk driver selection

---

source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Provide available nodes in VM info #104

Added 'Node' and 'Available Nodes' to vm 'info' output

---

source/usr/lib/mcvirt/constants.py
source/usr/lib/mcvirt/logger.py
source/usr/lib/mcvirt/mcvirt_config.py
source/usr/lib/mcvirt/rpc/lock.py
source/usr/lib/mcvirt/syslogger.py
source/usr/lib/mcvirt/system.py

Added class for hanlding logging instance and add logging to 'Log' class, system calls and lock

---

source/usr/lib/mcvirt/argument_validator.py
source/usr/lib/mcvirt/auth/auth.py
source/usr/lib/mcvirt/auth/factory.py
source/usr/lib/mcvirt/iso/factory.py
source/usr/lib/mcvirt/logger.py
source/usr/lib/mcvirt/test/test_base.py
source/usr/lib/mcvirt/test/virtual_machine/virtual_machine_tests.py
source/usr/lib/mcvirt/virtual_machine/factory.py
source/usr/lib/mcvirt/virtual_machine/hard_drive/factory.py
source/usr/lib/mcvirt/virtual_machine/network_adapter/factory.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py

Updated various exposed methods to use verify all arguments

Added class to validate various types of arguments.

---

CHANGES

I've been looking at all the commits between the v3.0.0 tag and current master on [this page](https://github.com/ITDevLtd/MCVirt/compare/v3.0.0...master), and have added everything I think is needed.
A lot of the work done was updating things to work with the Pyro stuff so I don't think needs to be included in the release notes.

Update CHANGES for v4.0.0

---

source/usr/lib/mcvirt/exceptions.py
source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/virtual_machine/factory.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine_config.py

* Add `--graphics-driver` option to create and update parsers
* Set/update graphics driver in VM config and libvirt config
* Rename driver` option to `--hdd-driver` in create and update parsers

Support alternative graphics drivers

---

source/usr/lib/mcvirt/exceptions.py
source/usr/lib/mcvirt/parser.py
source/usr/lib/mcvirt/test/unit_test_bootstrap.py
source/usr/lib/mcvirt/test/update_tests.py
source/usr/lib/mcvirt/virtual_machine/factory.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine.py
source/usr/lib/mcvirt/virtual_machine/virtual_machine_config.py

* Add `--set-win10` option to create parser to add Windows 10 CPU flags to VM and libvirt configs
* Add `--set-win10` and `--unset-win10` to update parser to add/remove Windows 10 CPU flags
* Add unit test

Add support for Windows 10

---

source/usr/lib/python2.7/dist-packages/mcvirt/rpc/expose_method.py
source/usr/lib/python2.7/dist-packages/mcvirt/storage/lvm.py
source/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/hard_drive/base.py
source/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/hard_drive/drbd.py
source/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/hard_drive/local.py
source/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine.py

Update hard drive factory new expose

---

source/usr/lib/python2.7/dist-packages/mcvirt/argument_validator.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/auth.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/factory.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/group/factory.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/group/group.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/permissions.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/user_types/ldap_user.py
source/usr/lib/python2.7/dist-packages/mcvirt/auth/user_types/user_base.py
source/usr/lib/python2.7/dist-packages/mcvirt/cluster/cluster.py
source/usr/lib/python2.7/dist-packages/mcvirt/config_file.py
source/usr/lib/python2.7/dist-packages/mcvirt/constants.py
source/usr/lib/python2.7/dist-packages/mcvirt/exceptions.py
source/usr/lib/python2.7/dist-packages/mcvirt/mcvirt_config.py
source/usr/lib/python2.7/dist-packages/mcvirt/parser.py
source/usr/lib/python2.7/dist-packages/mcvirt/rpc/expose_method.py
source/usr/lib/python2.7/dist-packages/mcvirt/rpc/pyro_object.py
source/usr/lib/python2.7/dist-packages/mcvirt/rpc/rpc_daemon.py
source/usr/lib/python2.7/dist-packages/mcvirt/storage/base.py
source/usr/lib/python2.7/dist-packages/mcvirt/test/auth_tests.py
source/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine.py
source/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine_config.py

Start work towards #29, #293 and #332.

Create dynamic groups

---

source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/storage.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/parser_modules/storage_parser.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/rpc/expose_method.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/storage/base.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/storage/factory.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine.py

Update storage to use custom config class

---

source/mcvirt-agent/usr/lib/python2.7/dist-packages/mcvirt/agent/host_connection.py
source/mcvirt-common/DEBIAN/control
source/mcvirt-common/usr/lib/python2.7/dist-packages/mcvirt/os_stats.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/base.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/core.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/migrations/core/v20.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/rpc/rpc_daemon.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/thread/statistics.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine.py

Add daemon to monitor guest statistics and update agent to return cpu/memory usage

Monitor vm statistics

---

source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine.py

Specify units of Bytes when providing memory

Fix memory allocation to VM. #439

---

source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/base.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/migrations/virtual_machine/v22.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/config/virtual_machine.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/exceptions.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/parser_modules/virtual_machine/update_parser.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/hard_drive_attachment.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/network_adapter/network_adapter.py
source/mcvirt-daemon/usr/lib/python2.7/dist-packages/mcvirt/virtual_machine/virtual_machine.py

450 add memballoon support
